# Generated by Django 4.2.3 on 2023-12-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_company_person_remove_persondata_company_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="persondata",
            name="camera_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="persondata",
            name="class_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="persondata",
            name="count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="persondata",
            name="date_created",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="persondata",
            name="time_created",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
