# Generated by Django 4.2.7 on 2023-12-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_persondata_camera_name_persondata_class_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="persondata",
            name="camera_name",
        ),
        migrations.AddField(
            model_name="persondata",
            name="camera",
            field=models.ForeignKey(
                default=1.2,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.camera",
            ),
            preserve_default=False,
        ),
    ]
