# Generated by Django 4.2.7 on 2023-12-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_camera_remove_persondata_camera_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="company_id",
            field=models.CharField(default=1.2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="employee_id",
            field=models.CharField(default=1.2, max_length=50),
            preserve_default=False,
        ),
    ]
