# Generated by Django 4.2.7 on 2023-12-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_person_company_id_person_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=200)),
                ('cam_name', models.CharField(default=True, max_length=100)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(max_length=200)),
                ('username', models.CharField(default=True, max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, default=True, max_length=100, null=True)),
            ],
        ),
    ]
