# Generated by Django 4.2.7 on 2023-12-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_serverinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
