# Generated by Django 4.2.7 on 2023-12-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_serverinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCameraAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.serverinfo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person')),
            ],
        ),
    ]
